### ISSUE TITLE
nicoJS.send()が透明になる

### ISSUE THREAD

**Issue by yuta0801** [yuki540net/nicoJS#3]
nicoJS.send()が透明になっていまいます。

DeveloperToolからは動いているのは確認できたのですが、文字色が透明になってしまいます。

nicoJS.loop()のほうは正しく表示されました。
v1.1.6にダウングレードしたところ同じソースで正しく表示されました。

**Comment by yui540** [comment]
今日中に修正しますので少々お待ちください。

**Comment by yui540** [comment]
```bash
npm update nicojs
```
nicojs@1.1.8をお使いください。
